### ISSUE TITLE
Can't build external go module via importing klaytn

### ISSUE THREAD

**Issue by NEO2756** [klaytn/klaytn#277]
**Describe the bug**
Error while building external go module. 
I am importing klaytn source file as klaytn don't have go client library.
**LOGS:**
**sandeeps-MBP:launcher-docker neo$ go version
go version go1.12.6 darwin/amd64**

sandeeps-MBP:launcher-docker neo$ go build
github.com/klaytn/klaytn/networks/rpc
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/networks/rpc/server.go:57:3: cannot use set.New() (type set.Interface) as type *set.Set in field value: need type assertion
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/networks/rpc/server.go:57:20: not enough arguments in call to set.New
have ()
want (set.SetType)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/networks/rpc/websocket.go:145:20: not enough arguments in call to set.New
have ()
want (set.SetType)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/networks/rpc/websocket.go:183:20: not enough arguments in call to set.New
have ()
want (set.SetType)
github.com/klaytn/klaytn/storage/database
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:42:6: opts.Dir undefined (type func(string) badger.Options has no field or method Dir)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:43:6: opts.ValueDir undefined (type func(string) badger.Options has no field or method ValueDir)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:45:2: cannot use opts (type func(string) badger.Options) as type badger.Options in return argument
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:126:19: too many arguments in call to txn.Commit
have (nil)
want ()
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:137:13: assignment mismatch: 2 variables but item.Value returns 1 values
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:137:26: not enough arguments in call to item.Value
have ()
want (func([]byte) error)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:149:2: not enough arguments to return
have (error)
want ([]byte, error)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:149:19: not enough arguments in call to item.Value
have ()
want (func([]byte) error)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:160:19: too many arguments in call to txn.Commit
have (nil)
want ()
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:204:21: too many arguments in call to b.txn.Commit
have (nil)
want ()
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:204:21: too many errors
github.com/klaytn/klaytn/accounts/keystore
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/accounts/keystore/account_cache.go:87:26: undefined: set.NewNonTS
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/accounts/keystore/file_cache.go:56:9: undefined: set.NewNonTS
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/accounts/keystore/file_cache.go:57:10: undefined: set.NewNonTS

**How to reproduce**
import klaytn ( speacifically "github.com/klaytn/klaytn/client")!!

**Expected behavior**
My module should build

**Environment (please complete the following information)**
 - Using  https://api.baobab.klaytn.net provider
 - go version `$ go version`
 - OS and its version [e.g. macOS/10.14]

**Comment by NEO2756** [comment]
anybody here ?

**Comment by kjhman21** [comment]
@jeonghonah Please take care of this issue.
@NEO2756 We are trying to change the import mechanism in klaytn. Once it is finished, I think this issue will be resolved. Thanks for the reporting.

**Comment by jeonghonah** [comment]
@NEO2756 It might be a duplicated issue with #210. Applying PR #281 tested that the issue has been resolved.

**Comment by NEO2756** [comment]
> @NEO2756 It might be a duplicated issue with #210. Applying PR #281 tested that the issue has been resolved.
I tried fetching PR #281 locally and tried building, still facing same issue.

**Comment by jeonghonah** [comment]
@NEO2756 Please reopen this issue if the problem is not solved.
